print(" |\/\/\/| ")
print(" |      | ")
print(" |      | ")
print(" | (o)(o) ")
print(" C      _)")
print("  | ,___| ")
print("  |   /   ")
print(" /____\   ")
print("/      \  ")

print("      &      ")
print("   .-""-.   ")
print("  /       \  ")
print("  |   __  _| ")        
print("  |  /  \/ \ ")
print(" WW  \_o/_o/ ")
print(" (        _) ")
print("  |  .---- \ ")
print("  ; | '---- '")
print("   \__'--;`  ")
print(    |___/\|   ")
